[package]
name = "haven-ui"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
backer = { path = "../backer" }
lilt = "0.7.0"
parley = "0.2.0"
pollster = "0.4.0"
vello = { git = "https://github.com/waywardmonkeys/vello", branch = "update-to-wgpu-23" }
winit = "0.30.5"
