[package]
name = "haven"
version = "0.1.0"
edition = "2021"

[[example]]
name = "basic"
path = "examples/basic/src/main.rs"

[dependencies]
backer = { path = "../backer" }
lilt = "0.7.0"
parley = "0.2.0"
pollster = "0.4.0"
vello = "0.3.0"
winit = "0.30.5"
