[package]
name = "ui"
version = "0.1.0"
edition = "2021"
publish = false

[[example]]
name = "basic"
path = "examples/basic/src/main.rs"

[dependencies]
backer = { path = "../backer" }
lilt = "0.7.0"
parley = { git = "https://github.com/linebender/parley", branch = "main" }
pollster = "0.4.0"
vello_svg = { version = "0.6.0", features = ["wgpu"] }
winit = "0.30.8"
