mod animated_color;
mod app;
mod button;
mod circle;
mod editor;
mod event;
mod gestures;
mod models;
mod rect;
mod scroller;
mod shape;
mod svg;
mod text;
mod toggle;
mod ui;
mod view;

pub use app::App;
pub use backer::{models::*, nodes::*, Layout, Node};
pub use button::*;
pub use circle::circle;
pub use editor::*;
pub use gestures::{ClickState, DragState, GestureHandler, GestureState};
use lilt::Easing;
pub use rect::rect;
pub use scroller::*;
pub use svg::svg;
pub use text::*;
pub use toggle::*;
pub use ui::{scoper, RcUi, Ui};
pub use vello_svg::vello::kurbo::*;
use vello_svg::vello::peniko::color::AlphaColor;
use vello_svg::vello::peniko::color::Srgb;
pub use vello_svg::vello::peniko::Color;
pub use view::clipping;
pub use view::const_hash;
pub use view::custom_view;
pub use view::dynamic_node;
pub use winit::keyboard::NamedKey;

pub use models::*;

const RUBIK_FONT: &[u8] = include_bytes!("../assets/Rubik-VariableFont_wght.ttf");
const DEFAULT_EASING: Easing = Easing::EaseOut;
const DEFAULT_DURATION: f32 = 200.;
const DEFAULT_PADDING: f32 = 10.;
const DEFAULT_CORNER_ROUNDING: f32 = 20.;
const DEFAULT_FONT_SIZE: u32 = 14;
const DEFAULT_FG_COLOR: AlphaColor<Srgb> = AlphaColor::WHITE;
